---
title: "KEGG network"
author: "Zhifeng Yang"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(KEGGgraph)
library(RBGL)
library(igraph)
library(plyr)
```

## A whole KEGG network of E.coli

```{r}
mapfile <-  "xml/eco01100.xml"
map <- parseKGML(mapfile)
map
reactions <- getReactions(map)
```


```{r}



###################################################
### code chunk number 20: cnexample
###################################################
chemicalGraph <- KEGGpathway2reactionGraph(map)

outDegrees <- sapply(edges(chemicalGraph), length)
maxout <- names(sort(outDegrees,decreasing=TRUE))[1:3]

nAttrs <- list()
maxoutlabel <- as.list(maxout); names(maxoutlabel) <- maxout
nAttrs$label <- makeAttr(chemicalGraph, "", maxoutlabel)
nAttrs$fillcolor <- makeAttr(chemicalGraph, "lightblue", list(orange=maxout))
nAttrs$width <- makeAttr(chemicalGraph,"0.8", list("1.8"=maxout))
plot(chemicalGraph, nodeAttrs=nAttrs)


```
```{r}

g=graph_from_graphnel(chemicalGraph)
S=induced.subgraph(g, which(members == which(table(members)==max(table(members)))))
plot(S,vertex.label=NA)

members <- membership(clusters(graph_from_graphnel(chemicalGraph), mode="strong"))
strongly_connected=lapply(unique(members), function (x) induced.subgraph(graph_from_graphnel(chemicalGraph), which(members == x)))

strongly_connected[[1]]
plot(graph_from_graphnel(chemicalGraph))
strongly_connected
```




```{r}
url=getKGMLurl("eco01100",organism ="eco")
download.file(url, "xml/eco01100.xml")
```



















